name: QA Deployment Validation

on:
  push:
    branches:
      - "**"        # kisi bhi branch se push ho
  pull_request:
    branches:
      - sandbox
      - main

jobs:
  validate-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Authenticate to QA Org
        run: |
          echo "${{ secrets.SF_QA_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias qa --set-default

      - name: Validate deployment to QA (Check Only)
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org qa \
            --check-only \
            --test-level RunLocalTests \
            --wait 30
